SELECT * FROM LEAVE_RECORDS;
SELECT * FROM PAYROLL;
SELECT * FROM DEPARTMENTS;
SELECT * FROM POSITIONS;
SELECT * FROM EMPLOYEES;

DESCRIBE EMPLOYEES;
DESCRIBE POSITIONS;
DESCRIBE LEAVE_RECORDS;
DESCRIBE DEPARTMENTS;
DESCRIBE PAYROLL;